# Generated by cpp11: do not edit by hand

mcmc_cpp <- function(data_list, obs_time_list, obs_time_start, obs_time_end, haplo_freqs, iterations, burnin, param_list, param_update_list, proposal_sd, lambda_prior, theta_prior, decay_rate_prior, sens_prior, iteration_counter_init, beta, max_infections, rng_ptr, interactive) {
  .Call(`_GLAM_mcmc_cpp`, data_list, obs_time_list, obs_time_start, obs_time_end, haplo_freqs, iterations, burnin, param_list, param_update_list, proposal_sd, lambda_prior, theta_prior, decay_rate_prior, sens_prior, iteration_counter_init, beta, max_infections, rng_ptr, interactive)
}

debug_algo1_cpp <- function(data_list, obs_time_list, obs_time_start, obs_time_end, haplo_freqs, param_list, param_update_list, proposal_sd, lambda_prior, theta_prior, decay_rate_prior, sens_prior, beta, max_infections, rng_ptr) {
  invisible(.Call(`_GLAM_debug_algo1_cpp`, data_list, obs_time_list, obs_time_start, obs_time_end, haplo_freqs, param_list, param_update_list, proposal_sd, lambda_prior, theta_prior, decay_rate_prior, sens_prior, beta, max_infections, rng_ptr))
}
