# Generated by cpp11: do not edit by hand

mcmc_cpp <- function(data_list, obs_time_list, haplo_freqs, iterations, burnin, param_list, param_update_list, proposal_sd, iteration_counter_init, beta, start_time, end_time, max_infections, rng_ptr) {
  .Call(`_GLAM_mcmc_cpp`, data_list, obs_time_list, haplo_freqs, iterations, burnin, param_list, param_update_list, proposal_sd, iteration_counter_init, beta, start_time, end_time, max_infections, rng_ptr)
}

debug_algo1_cpp <- function(data_list, obs_time_list, haplo_freqs, param_list, param_update_list, proposal_sd, beta, start_time, end_time, max_infections, rng_ptr) {
  invisible(.Call(`_GLAM_debug_algo1_cpp`, data_list, obs_time_list, haplo_freqs, param_list, param_update_list, proposal_sd, beta, start_time, end_time, max_infections, rng_ptr))
}
