# Generated by cpp11: do not edit by hand

mcmc_cpp <- function(data_list, obs_time_list, iterations, burnin, param_list, proposal_sd, iteration_counter_init, beta, start_time, end_time, rng_ptr) {
  .Call(`_GLAM_mcmc_cpp`, data_list, obs_time_list, iterations, burnin, param_list, proposal_sd, iteration_counter_init, beta, start_time, end_time, rng_ptr)
}
